GET http://localhost:3001/
###
GET http://localhost:3001/api/blogs/
###
GET http://localhost:3001/api/users/
###
GET http://localhost:3001/api/blogs/2
###
DELETE http://localhost:3001/api/blogs/649ca0c266d4e9ffd3e0002c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdWtra2trIiwiaWQiOiI2NGFhZjU1OGY2MmFjNDRmMDViMDc2NjYiLCJpYXQiOjE2ODg5MjU3MTB9.FoinEH17ATldVjIhoX2FCpaP6Xb9ONls8o-H_uph5L8
###
POST http://localhost:3001/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdWtra2trIiwiaWQiOiI2NGFhZjU1OGY2MmFjNDRmMDViMDc2NjYiLCJpYXQiOjE2ODg5MjU3MTB9.FoinEH17ATldVjIhoX2FCpaP6Xb9ONls8o-H_uph5L8

{
    "title": "Awesome text",
    "author": "Some James",
    "url": "https://wwww.google.com",
    "likes": 90
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "mlukkkkk",
    "name": "Matti Luukkainepn",
    "password": "salainenf"
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "mlukkkkk",
    "password": "salainenf"
}

###
PUT http://localhost:3001/api/blogs/648c9edd1749e10940f89e39
content-type: application/json

{
    "title": "Awesome text jjj",
    "author": "Some James",
    "url": "https://wwww.google.com",
    "likes": "45",
    "user": "6488a708f136a179aaa18d15"
}